app:
  build: .
  volumes:
    - ..:/srv/wfgn
  environment:
    - "POLICY_SERVER=false"
    - "SERVER_NAME=localhost:80"
  expose:
    - "8001"
  command: gunicorn runserver:app -b :8001 -w 1 --worker-class socketio.sgunicorn.GeventSocketIOWorker --log-level debug --error-logfile /dev/stdout --access-logfile /dev/stdout

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  expose:
    - "80"
  volumes_from:
    - app

vanilla:
  build: .
  volumes:
    - ..:/srv/wfgn
  ports:
    - "5000:5000"
  command: ./runserver.py

gunicorn:
  build: .
  volumes:
    - ..:/srv/wfgn
  environment:
    - "POLICY_SERVER=false"
    - "SERVER_NAME=localhost:8001"
  ports:
    - "8001:8001"
  command: gunicorn runserver:app -b :8001 -w 1 --worker-class socketio.sgunicorn.GeventSocketIOWorker --log-level debug --error-logfile /dev/stdout --access-logfile /dev/stdout
